### PR TITLE
MLR-105: Initial docker swarm investigation for Keycloak

### PR DESCRIPTION
**Pull request by zmoore-usgs**

### CODE REVIEW

**Comment by zmoore-usgs** [comment]
For some reason it won't let me request a review from you, @ayan-usgs. Not sure why

**Comment by zmoore-usgs** [comment]
@dsteinich Out of curiosity, which part fails on your machine? 

I'll start creating the outline of a deployment plan for this and an accompanying RDS, though I don't know much about CHS deployments yet so I'll need to work with you or @ayan-usgs sometime on actually filling in the details.

**Comment by dsteinich** [comment]
It started going south at the registry creation:
```
image registry:2 could not be accessed on a registry to record
its digest. Each node will access registry:2 independently,
possibly leading to different nodes running different
versions of the image.
```
And kept getting worse with the docker-machine setup/interactions from there...

**Comment by zmoore-usgs** [comment]
Huh, that's really strange. I pulled the registry creation step directly from the Docker documentation: https://docs.docker.com/engine/swarm/stack-deploy/#set-up-a-docker-registry

I'm not sure why your docker installation can't seem to find the registry image..

**Pull request merged**
